apiVersion: apps/v1
kind: Deployment
metadata:
  name: appv1
  labels:
    cannary: app
spec:
  replicas: 3
  selector:
    matchLabels:
      cannary: app
  template:
    metadata:
      labels:
        cannary: app
    spec:
      containers:
        - name: appv1
          image: nginx:1.19
